language: php

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
  - mongodb

cache:
    directories:
      - "$HOME/.composer/cache"
      - "$HOME/.npm"

matrix:
  include:
    - php: 5.6
    - php: 7.1
    - php: 7.2
      env: COVERAGE=yes
    - php: 7.2
      env: SUBSPLIT=yes
      deploy:
        provider: script
        script: bash etc/travis/bin/split.sh
        skip_cleanup: true
        on:
          all_branches: true

before_install:
  - node --version
  # remove xdebug when not collecting code coverage
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;
  - pecl channel-update pecl.php.net

before_script:
  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # copy default app config
  - mkdir -p config/autoload
  - mkdir -p build/behat
  - mkdir -p build/mails
  - cp ./etc/travis/autoload/*.* config/autoload

  # install Mongo extension
  - pecl install -f mongodb
  - phpenv config-add etc/travis/phpenv.ini
  - composer install --prefer-dist --no-interaction

  # TODO: remove this line when composer auto-scripts automatically executed
  - composer run auto-scripts

  # setup display, behat, and selenium
  - ./bin/start-selenium > /dev/null 2>&1 &
  - sleep 5
  - composer run serve --timeout=0 > /dev/null 2>&1 &
  - sleep 3

script:
  - 'if [[ $COVERAGE = yes ]]; then
        ./vendor/bin/phpunit --verbose --coverage-clover=build/logs/clover.xml --coverage-php=build/logs/clover.serialized;
    else
        ./vendor/bin/phpunit --verbose;
    fi'
  # only run behat tests when not collecting coverage
  - if [[ $COVERAGE != yes ]]; then APPLICATION_ENV=development ./vendor/bin/behat --strict --no-interaction; fi

after_failure:
  - cd $TRAVIS_BUILD_DIR
  - "./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles \"build/behat/*.log\""
  - "./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles \"log/*.log\""
  - "./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles \"log/tracy/*.*\""
  - "IMGUR_CLIENT_ID=bec050c54e1bb52 ./bin/imgur-uploader build/behat/*.png"

after_script:
  # process coverage
  - 'if [[ $COVERAGE = yes ]]; then
        composer require php-coveralls/php-coveralls --no-scripts;
        travis_retry vendor/bin/php-coveralls -vvv;
        wget https://scrutinizer-ci.com/ocular.phar;
        travis_retry ocular.phar code-coverage:upload --format=php-clover build/logs/clover.serialized;
    fi'